### PR TITLE
Define hooks for ember-cli-reporter plugins

### PR DESCRIPTION
**Pull request by binhums**
Finally got round to writing down my initial thoughts here. Allows definition of an ember-cli-reporter plugin.

Plugins register listeners on a `ember-cli-reporter` service and are expected to respond to the following events:

- `configure` - called when the app is initialized with the contents of `config/environment.js`.
- `error` - called when the application needs to report an error with an instance of the error.

Client installation would then be a case of

```
ember install ember-cli-reporter
ember install ember-cli-reporter-bugsnag
```

and defining config variables in `config/environment.js`

The intention is for the plugins to be similar in implementation e.g. through an instance initializer:

```js
import configureBugsnag from '../utils/configure-bugsnag';
import reportError from '../utils/report-error';

export function initialize(appInstance) {
  let lookupContext = appInstance.lookup ? appInstance : appInstance.container;

  let reporterService = lookupContext.lookup('service:ember-cli-reporter');

  reporterService.on('configure', (config) => {
    configureBugsnag(config);
  });

  reporterService.on('error', (error) => {
    reportError(error)
  });
}
```

With the benefit that `configureBugsnag` and `reportError` can be unit tested.

See [ember-cli-reporter-bugsnag](https://github.com/ember-cli-reporter/ember-cli-reporter-bugsnag/tree/233c360148626b969cfa3911f09766d9c5094465) for some of my ideas on how we could do this.

### Initial thoughts

1. Motivation for defining a service mainly comes from ember-cli-airbrake. The global state in ember-cli-bugsnag is managed in the global window instance of `Bugsnag` which is not ideal.
2. How do we ensure that plugins have had a chance to register against the service before triggering the `configure` event? This works for me in testing but is there a better place to trigger the event?
3. Is there a way we can get plugins to auto register, like they do in ember-cli-deploy
3. I think the `configure` event should actually pass in a subset of `config/environment.js`, e.g. `config['reporter']['plugins']`. Any thoughts on naming conventions?
4. This design is based on ember error reporting addons and shared plugin ecosystems. Initially these hooks should cover the functionality needed for:

- ember-cli-deploy
- ember-metrics
- ember-cli-airbrake
- ember-bugsnag
- ember-cli-raygun
- ember-cli-rollbar

I know that ember-cli-bugsnag does some [funky stuff with the router](https://github.com/twokul/ember-cli-bugsnag/blob/6e87f7aebccecf1c9d5ac0059ca023c1e2b9a25f/app/instance-initializers/bugsnag.js#L26), because the plugin is an ember addon this should still work with this framework.

I've not yet looked at

- https://github.com/sir-dunxalot/ember-new-relic

### CODE REVIEW

**Comment by mmun** [comment]
I love it!

**Comment by binhums** [comment]
This excludes a strategy for catching errors before Ember starts up. I think it should be easy enough to queue them up until the `ember-cli-reporter` service becomes available.

**Comment by binhums** [comment]
I need to restructure this outside of initializers and services. Stand by.

**Comment by binhums** [comment]
@mmun what do you think of this instead. Plugins register through the app config, see ember-cli-reporter-bugsnag for an example.

Users can add plugin specific config like this.

```
     reporter: {
       pluginsConfig: {
         'ember-cli-reporter-bugsnag': {
           apiKey: 'shhhhhh',
           notifyReleaseStages: ['production', 'development']
         }
       }
     }
```

**Comment by mmun** [comment]
Can we just do `ember-cli-reporter-bugsnag` at the top-level?

**Comment by binhums** [comment]
Yes I think that's probably the best way to do it. Looking into setting that up.

**Comment by binhums** [comment]
@mmun added a README based on our latest discussions. Will merge if there are no further comments.

**Pull request merged**
